[project]
name = "analysis-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp>=1.8.1",
    "openai>=1.78.1",
    "openai-agents>=0.0.14",
]
